# Copyright (c) 2018-2022, NVIDIA CORPORATION.

# Usage:
#   conda build -c rapidsai -c conda-forge -c nvidia .
{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') + environ.get('VERSION_SUFFIX', '') %}
{% set minor_version =  version.split('.')[0] + '.' + version.split('.')[1] %}
{% set py_version=environ.get('CONDA_PY', 36) %}
package:
  name: cugraph_pyg
  version: {{ version }}

source:
  git_url: ../../..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: cuda{{ cuda_major }}_py{{ py_version }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
  script_env:
    - PARALLEL_LEVEL
  preserve_egg_dir: True

requirements:
  build:
    - sysroot_{{ target_platform }} {{ sysroot_version }}
  host:
    - python x.x
    - cython>=0.29,<0.30
    - scikit-build>=0.13.1
    # FIXME: this pin can be removed once we move to the GitHub Actions build process
    - setuptools<=65.2.0
  run:
    - distributed>=2022.9.2

tests:                                 # [linux64]
  requirements:                        # [linux64]
    - cudatoolkit {{ cuda_version }}.* # [linux64]
  imports:                             # [linux64]
    - cugraph                          # [linux64]
    - cugraph_pyg                      # [linux64]

about:
  home: http://rapids.ai/
  license: Apache-2.0
  license_file: ../../../LICENSE
  summary: cuGraph_pyg library
